name: Update README ⭐
on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          userId: 1511815
          sessionCookie: ${{ secrets.AOC_SESSION }}
          headerPrefix: "###"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
          file_pattern: README.md
